// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function CreateTodo(arg1:repository.Todo):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function ListTodos():Promise<Array<repository.Todo>>;
