// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:main.Todo):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function ListTodo():Promise<Array<main.Todo>>;
