// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function ListTodos() {
  return window['go']['main']['App']['ListTodos']();
}
